<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class RincianAnggaranSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Data diambil dari Lampiran I & II Peraturan Rektor No: 220.A/PR/REK/III/2025
        // Tentang Standar Biaya Operasional (SBO) Universitas Tiga Serangkai

        $data = [
[
        'kode_anggaran' => 'A.1.1',
        'nama_anggaran' => 'Kudapan Rapat',
        'satuan' => 'Orang/Hari',
        'nominal' => 10000,
    ],
    [
        'kode_anggaran' => 'A.1.2',
        'nama_anggaran' => 'Prasmanan',
        'satuan' => 'Orang/Hari',
        'nominal' => 90000,
    ],
    [
        'kode_anggaran' => 'A.1.3',
        'nama_anggaran' => 'Makan Panitia',
        'satuan' => 'Orang/Hari',
        'nominal' => 25000,
    ],
    [
        'kode_anggaran' => 'A.1.3',
        'nama_anggaran' => 'Kudapan Panitia',
        'satuan' => 'Orang/Hari',
        'nominal' => 10000,
    ],
    [
        'kode_anggaran' => 'A.1.3',
        'nama_anggaran' => 'Konsumsi Wisudawan dan Orang Tua',
        'satuan' => 'Orang/Hari',
        'nominal' => 30000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => 'Paket Halfday Orang/Hari',
        'satuan' => 'Paket',
        'nominal' => 150000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => 'Paket Fullday Orang/Hari',
        'satuan' => 'Paket',
        'nominal' => 250000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => 'Paket Fullboard Orang/Hari',
        'satuan' => 'Paket',
        'nominal' => 600000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '1. Aceh 300.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 370000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '2. Sumatera Utara 178.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 275000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '3. Riau 185.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 255000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '4. Kepulauan Riau 227.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 297000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '5. Jambi Orang/Paket 215.000',
        'satuan' => 'Jam',
        'nominal' => 301000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '6. Sumatera Barat 178.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 248000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '7. Sumatera Selatan 218.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 293000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '8. Lampung 220.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 290000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '9. Bengkulu 214.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 284000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '10. Bangka Belitung 299.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 385000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '11. Banten 330.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 425000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '12. Jawa Barat 331.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 401000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '13. D.K.I Jakarta 354.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 433000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '14. Jawa Tengah 191.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 263000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '15. D.I Yogyakarta 210.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 310000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '16. Jawa Timur 338.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 408000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '17. Bali 330.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 441000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '18. Nusa Tenggara Barat 317.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 420000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '19. Nusa Tenggara Timur 271.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 377000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '20. Kalimantan Barat Orang/Paket 250.000',
        'satuan' => 'Kali',
        'nominal' => 331000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '21. Kalimantan Tengah Orang/Paket 242.000',
        'satuan' => 'Kali',
        'nominal' => 340000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '22. Kalimantan Selatan Orang/Paket 200.000',
        'satuan' => 'Kali',
        'nominal' => 295000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '23. Kalimantan Timur Orang/Paket 207.000',
        'satuan' => 'Kali',
        'nominal' => 302000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '24. Kalimantan Utara Orang/Paket 207.000',
        'satuan' => 'Kali',
        'nominal' => 302000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '25. Sulawesi Utara 189.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 270000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '26. Gorontalo 175.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 250000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '27. Sulawesi Barat 235.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 323000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '28. Sulawesi Selatan 206.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 320000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '29. Sulawesi Tengah 260.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 385000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '30. Sulawesi Tenggara 225.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 295000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '31. Maluku 265.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 346000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '32. Maluku Utara 203.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 354000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '33. Papua 293.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 478000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '34. Papua Barat 310.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 421000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '1. Aceh 1.385.000 1.075.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 772000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '2. Sumatera Utara 1.350.000 1.011.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 764000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '3. Riau 1.182.000 867.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 655000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '4. Kepulauan Riau 1.187.000 987.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 697000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '5. Jambi Orang/Paket 1.230.000 1.038.000',
        'satuan' => 'Jam',
        'nominal' => 840000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '6. Sumatera Barat 1.492.000 987.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 663000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '7. Sumatera Selatan 1.214.000 895.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 745000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '8. Lampung 1.200.000 918.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 768000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '9. Bengkulu 1.262.000 1.062.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 912000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '10. Bangka Belitung 1.305.000 1.115.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 965000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '11. Banten 1.401.000 1.201.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 1005000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '12. Jawa Barat 1.914.000 1.110.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 822000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '13. D.K.I Jakarta 2.257.000 1.347.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 1197000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '14. Jawa Tengah 1.340.000 879.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 675000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '15. D.I Yogyakarta 1.454.000 963.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 750000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '16. Jawa Timur 2.159.000 1.784.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 1352000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '17. Bali 2.060.000 1.569.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 1419000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '18. Nusa Tenggara Barat 1.413.000 1.213.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 820000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '19. Nusa Tenggara Timur 1.288.000 1.088.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 825000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '20. Kalimantan Barat Orang/Paket 1.247.000 1.047.000',
        'satuan' => 'Kali',
        'nominal' => 744000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '21. Kalimantan Tengah Orang/Paket 1.721.000 1.521.000',
        'satuan' => 'Kali',
        'nominal' => 1170000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '22. Kalimantan Selatan Orang/Paket 1.150.000 975.000',
        'satuan' => 'Kali',
        'nominal' => 800000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '23. Kalimantan Timur Orang/Paket 1.250.000 1.050.000',
        'satuan' => 'Kali',
        'nominal' => 900000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '24. Kalimantan Utara Orang/Paket 1.218.000 1.025.000',
        'satuan' => 'Kali',
        'nominal' => 750000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '25. Sulawesi Utara 1.250.000 1.050.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 737000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '26. Gorontalo 1.738.000 1.538.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 1299000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '27. Sulawesi Barat 1.301.000 1.101.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 951000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '28. Sulawesi Selatan 1.774.000 1.574.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 1127000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '29. Sulawesi Tengah 1.416.000 1.216.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 886000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '30. Sulawesi Tenggara 1.335.000 885.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 695000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '31. Maluku 1.500.000 1.300.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 746000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '32. Maluku Utara 1.220.000 1.050.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 803000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '33. Papua 2.063.000 1.863.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 990000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '34. Papua Barat 1.952.000 1.752.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 1120000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '1. Aceh 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '2. Sumatera Utara 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '3. Riau 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '4. Kepulauan Riau 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '5. Jambi Orang/Paket 175.000 150.000',
        'satuan' => 'Jam',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '6. Sumatera Barat 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '7. Sumatera Selatan 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '8. Lampung 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '9. Bengkulu 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '10. Bangka Belitung 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '11. Banten 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '12. Jawa Barat 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '13. D.K.I Jakarta 200.000 175.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 150000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '14. Jawa Tengah 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 100000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '15. D.I Yogyakarta 150.000 125.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 100000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '16. Jawa Timur 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '17. Bali 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '18. Nusa Tenggara Barat 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '19. Nusa Tenggara Timur 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '20. Kalimantan Barat Orang/Paket 175.000 150.000',
        'satuan' => 'Kali',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '21. Kalimantan Tengah Orang/Paket 175.000 150.000',
        'satuan' => 'Kali',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '22. Kalimantan Selatan Orang/Paket 175.000 150.000',
        'satuan' => 'Kali',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '23. Kalimantan Timur Orang/Paket 175.000 150.000',
        'satuan' => 'Kali',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '24. Kalimantan Utara Orang/Paket 175.000 150.000',
        'satuan' => 'Kali',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '25. Sulawesi Utara 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '26. Gorontalo 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '27. Sulawesi Barat 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '28. Sulawesi Selatan 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '29. Sulawesi Tengah 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '30. Sulawesi Tenggara 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '31. Maluku 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '32. Maluku Utara 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '33. Papua 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.2',
        'nama_anggaran' => '34. Papua Barat 175.000 150.000',
        'satuan' => 'Orang/Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'A.5',
        'nama_anggaran' => 'Satuan Biaya Transportasi Kegiatan di Wilayah Orang/Kali',
        'satuan' => 'Kegiatan',
        'nominal' => 150000,
    ],
    [
        'kode_anggaran' => 'A.6',
        'nama_anggaran' => 'Bantuan BBM',
        'satuan' => 'Orang/Hari',
        'nominal' => 20000,
    ],
    [
        'kode_anggaran' => 'A.7',
        'nama_anggaran' => 'Akomodasi hotel dosen tamu',
        'satuan' => 'Orang/Hari',
        'nominal' => 750000,
    ],
    [
        'kode_anggaran' => 'A.7',
        'nama_anggaran' => 'Bantuan hosting tamu asing (banner, konsumsi',
        'satuan' => 'Orang/Kegiatan',
        'nominal' => 2000000,
    ],
    [
        'kode_anggaran' => 'A.7',
        'nama_anggaran' => '2. Honorarium Pengajar Oleh Instruktur Industri',
        'satuan' => 'SKS/Hadir',
        'nominal' => 150000,
    ],
    [
        'kode_anggaran' => 'A.7',
        'nama_anggaran' => '3. Honorarium Pengajar Oleh Asisten Dosen',
        'satuan' => 'SKS/Hadir',
        'nominal' => 50000,
    ],
    [
        'kode_anggaran' => 'A.7',
        'nama_anggaran' => 'Honorarium Pembimbing Skripsi/Tugas Akhir',
        'satuan' => 'Orang/Mhs',
        'nominal' => 750000,
    ],
    [
        'kode_anggaran' => 'A.7',
        'nama_anggaran' => 'Honorarium Penguji Skripsi/Tugas Akhir',
        'satuan' => 'Orang/Mhs',
        'nominal' => 150000,
    ],
    [
        'kode_anggaran' => 'A.7',
        'nama_anggaran' => 'Honorarium Pembimbing PPL/Magang',
        'satuan' => 'Orang/Kegiatan',
        'nominal' => 600000,
    ],
    [
        'kode_anggaran' => 'A.7',
        'nama_anggaran' => '- Lektor Kepala',
        'satuan' => 'Paket',
        'nominal' => 350000,
    ],
    [
        'kode_anggaran' => 'A.7',
        'nama_anggaran' => '- Lektor',
        'satuan' => 'Paket',
        'nominal' => 300000,
    ],
    [
        'kode_anggaran' => 'A.7',
        'nama_anggaran' => '- Asisten Ahli',
        'satuan' => 'Paket',
        'nominal' => 250000,
    ],
    [
        'kode_anggaran' => 'A.7',
        'nama_anggaran' => '- Tenaga Pengajar',
        'satuan' => 'Paket',
        'nominal' => 200000,
    ],
    [
        'kode_anggaran' => 'B.2.5',
        'nama_anggaran' => '- Lektor Kepala Per Mahasiswa',
        'satuan' => 'Paket',
        'nominal' => 150000,
    ],
    [
        'kode_anggaran' => 'B.2.5',
        'nama_anggaran' => '- Lektor Per Mahasiswa',
        'satuan' => 'Paket',
        'nominal' => 125000,
    ],
    [
        'kode_anggaran' => 'B.2.5',
        'nama_anggaran' => '- Asisten Ahli Per Mahasiswa',
        'satuan' => 'Paket',
        'nominal' => 100000,
    ],
    [
        'kode_anggaran' => 'B.2.5',
        'nama_anggaran' => '- Tenaga Pengajar Per Mahasiswa',
        'satuan' => 'Paket',
        'nominal' => 75000,
    ],
    [
        'kode_anggaran' => 'B.2.5',
        'nama_anggaran' => 'Menteri/Pejabat setingkat Menteri',
        'satuan' => 'Orang/Jam',
        'nominal' => 1700000,
    ],
    [
        'kode_anggaran' => 'B.2.5',
        'nama_anggaran' => 'Pejabat Eselon I/yang disetarakan',
        'satuan' => 'Orang/Jam',
        'nominal' => 1400000,
    ],
    [
        'kode_anggaran' => 'B.2.5',
        'nama_anggaran' => 'Pejabat Eselon II/yang disetarakan',
        'satuan' => 'Orang/Jam',
        'nominal' => 1000000,
    ],
    [
        'kode_anggaran' => 'B.2.5',
        'nama_anggaran' => 'Pejabat Eselon III/yang disetarakan',
        'satuan' => 'Orang/Jam',
        'nominal' => 900000,
    ],
    [
        'kode_anggaran' => 'B.2.5',
        'nama_anggaran' => 'Praktisi/Pakar/Profesional',
        'satuan' => 'Orang/Jam',
        'nominal' => 1700000,
    ],
    [
        'kode_anggaran' => 'B.2.5',
        'nama_anggaran' => 'Moderator',
        'satuan' => 'Orang/Datang',
        'nominal' => 700000,
    ],
    [
        'kode_anggaran' => 'B.2.5',
        'nama_anggaran' => 'Pembawa Acara',
        'satuan' => 'Orang/Datang',
        'nominal' => 400000,
    ],
    [
        'kode_anggaran' => 'B.2.5',
        'nama_anggaran' => 'Honor jasa pengelola webinar (host, co- host)',
        'satuan' => 'Orang/Kegiatan',
        'nominal' => 150000,
    ],
    [
        'kode_anggaran' => 'B.3.2',
        'nama_anggaran' => 'Eselon I/yang disetarakan',
        'satuan' => 'Orang/Jam',
        'nominal' => 2100000,
    ],
    [
        'kode_anggaran' => 'B.3.2',
        'nama_anggaran' => 'Pejabat Eselon II/yang disetarakan',
        'satuan' => 'Orang/Jam',
        'nominal' => 1500000,
    ],
    [
        'kode_anggaran' => 'B.3.2',
        'nama_anggaran' => 'Pejabat Eselon III/yang disetarakan',
        'satuan' => 'Orang/Jam',
        'nominal' => 1350000,
    ],
    [
        'kode_anggaran' => 'B.3.2',
        'nama_anggaran' => 'Praktisi/Pakar/Profesional',
        'satuan' => 'Orang/Jam',
        'nominal' => 2550000,
    ],
    [
        'kode_anggaran' => 'B.3.2',
        'nama_anggaran' => 'Moderator',
        'satuan' => 'Orang/Datang',
        'nominal' => 1050000,
    ],
    [
        'kode_anggaran' => 'B.3.2',
        'nama_anggaran' => 'Pembawa Acara',
        'satuan' => 'Orang/Datang',
        'nominal' => 600000,
    ],
    [
        'kode_anggaran' => 'B.3.2',
        'nama_anggaran' => 'Honor jasa pengelola webinar (host, co-',
        'satuan' => 'Orang/Kegiatan',
        'nominal' => 250000,
    ],
    [
        'kode_anggaran' => 'B.3.2',
        'nama_anggaran' => 'Pembuatan video webinar Internasional',
        'satuan' => 'Paket',
        'nominal' => 1000000,
    ],
    [
        'kode_anggaran' => 'B.3.2',
        'nama_anggaran' => 'Pembuatan website seminar Internasional',
        'satuan' => 'Paket',
        'nominal' => 7500000,
    ],
    [
        'kode_anggaran' => 'B.4.1',
        'nama_anggaran' => 'Penanggung Jawab Orang/ Kegiatan',
        'satuan' => 'Kegiatan',
        'nominal' => 450000,
    ],
    [
        'kode_anggaran' => 'B.4.1',
        'nama_anggaran' => 'Ketua Orang/ Kegiatan',
        'satuan' => 'Kegiatan',
        'nominal' => 400000,
    ],
    [
        'kode_anggaran' => 'B.4.1',
        'nama_anggaran' => 'Wakil Ketua Orang/ Kegiatan',
        'satuan' => 'Kegiatan',
        'nominal' => 350000,
    ],
    [
        'kode_anggaran' => 'B.4.1',
        'nama_anggaran' => 'Bendahara Orang/ Kegiatan',
        'satuan' => 'Kegiatan',
        'nominal' => 300000,
    ],
    [
        'kode_anggaran' => 'B.4.1',
        'nama_anggaran' => 'Sekretaris Orang/ Kegiatan',
        'satuan' => 'Kegiatan',
        'nominal' => 300000,
    ],
    [
        'kode_anggaran' => 'B.4.1',
        'nama_anggaran' => 'Koordinator Orang/ Kegiatan',
        'satuan' => 'Kegiatan',
        'nominal' => 300000,
    ],
    [
        'kode_anggaran' => 'B.4.1',
        'nama_anggaran' => 'Anggota Orang/ Kegiatan Orang/ Kegiatan',
        'satuan' => 'Kegiatan',
        'nominal' => 200000,
    ],
    [
        'kode_anggaran' => 'B.4.2',
        'nama_anggaran' => 'Pengarah',
        'satuan' => 'Orang/Bulan',
        'nominal' => 400000,
    ],
    [
        'kode_anggaran' => 'B.4.2',
        'nama_anggaran' => 'Penanggung Jawab',
        'satuan' => 'Orang/Bulan',
        'nominal' => 300000,
    ],
    [
        'kode_anggaran' => 'B.4.2',
        'nama_anggaran' => 'Ketua',
        'satuan' => 'Orang/Bulan',
        'nominal' => 300000,
    ],
    [
        'kode_anggaran' => 'B.4.2',
        'nama_anggaran' => 'Wakil Ketua',
        'satuan' => 'Orang/Bulan',
        'nominal' => 250000,
    ],
    [
        'kode_anggaran' => 'B.4.2',
        'nama_anggaran' => 'Sekretaris Orang/ Bulan',
        'satuan' => 'Bulan',
        'nominal' => 250000,
    ],
    [
        'kode_anggaran' => 'B.4.2',
        'nama_anggaran' => 'Bendahara Orang/ Bulan',
        'satuan' => 'Bulan',
        'nominal' => 250000,
    ],
    [
        'kode_anggaran' => 'B.4.2',
        'nama_anggaran' => 'Koordinator Orang/ Bulan',
        'satuan' => 'Bulan',
        'nominal' => 250000,
    ],
    [
        'kode_anggaran' => 'B.4.2',
        'nama_anggaran' => 'Anggota Orang/ Bulan',
        'satuan' => 'Bulan',
        'nominal' => 200000,
    ],
    [
        'kode_anggaran' => 'B.4.3',
        'nama_anggaran' => 'Penanggung Jawab Orang/Terbit',
        'satuan' => 'Paket',
        'nominal' => 500000,
    ],
    [
        'kode_anggaran' => 'B.4.3',
        'nama_anggaran' => 'Redaktur Orang/Terbit',
        'satuan' => 'Paket',
        'nominal' => 400000,
    ],
    [
        'kode_anggaran' => 'B.4.3',
        'nama_anggaran' => 'Penyunting/Editor Orang/Terbit',
        'satuan' => 'Paket',
        'nominal' => 300000,
    ],
    [
        'kode_anggaran' => 'B.4.3',
        'nama_anggaran' => 'Desain Grafis Orang/Terbit',
        'satuan' => 'Paket',
        'nominal' => 180000,
    ],
    [
        'kode_anggaran' => 'B.4.3',
        'nama_anggaran' => 'Fotografer Orang/Terbit',
        'satuan' => 'Paket',
        'nominal' => 180000,
    ],
    [
        'kode_anggaran' => 'B.4.3',
        'nama_anggaran' => 'Sekretariat Orang/Terbit',
        'satuan' => 'Paket',
        'nominal' => 150000,
    ],
    [
        'kode_anggaran' => 'B.4.4',
        'nama_anggaran' => 'Penanggung Jawab Orang/Terbit',
        'satuan' => 'Paket',
        'nominal' => 400000,
    ],
    [
        'kode_anggaran' => 'B.4.4',
        'nama_anggaran' => 'Redaktur Orang/Terbit',
        'satuan' => 'Paket',
        'nominal' => 500000,
    ],
    [
        'kode_anggaran' => 'B.4.4',
        'nama_anggaran' => 'Penyunting/Editor Orang/Terbit',
        'satuan' => 'Paket',
        'nominal' => 250000,
    ],
    [
        'kode_anggaran' => 'B.4.4',
        'nama_anggaran' => 'Desain Gratis Orang/Terbit',
        'satuan' => 'Paket',
        'nominal' => 180000,
    ],
    [
        'kode_anggaran' => 'B.4.5',
        'nama_anggaran' => 'Honorarium Rohaniawan',
        'satuan' => 'Orang/Datang',
        'nominal' => 250000,
    ],
    [
        'kode_anggaran' => 'B.4.6',
        'nama_anggaran' => 'Honorarium Wasit/Juri Nasional',
        'satuan' => 'Orang/Kegiatan',
        'nominal' => 500000,
    ],
    [
        'kode_anggaran' => 'B.4.6',
        'nama_anggaran' => 'Honorarium Wasit/Juri Lokal',
        'satuan' => 'Orang/Kegiatan',
        'nominal' => 300000,
    ],
    [
        'kode_anggaran' => 'B.4.7',
        'nama_anggaran' => 'Honorarium Narasumber/Assesor',
        'satuan' => 'Orang/Kegiatan',
        'nominal' => 500000,
    ],
    [
        'kode_anggaran' => 'B.4.8',
        'nama_anggaran' => 'Persiapan/Pantukir/Evaluasi dan Pelaporan',
        'satuan' => 'Orang/Kegiatan',
        'nominal' => 1000000,
    ],
    [
        'kode_anggaran' => 'B.4.8',
        'nama_anggaran' => 'Pelaksanaan Orang/ Kegiatan',
        'satuan' => 'Kegiatan',
        'nominal' => 2000000,
    ],
    [
        'kode_anggaran' => 'B.4.9',
        'nama_anggaran' => 'Persiapan/Pantukir/Evaluasi dan Pelaporan',
        'satuan' => 'Orang/Kegiatan',
        'nominal' => 800000,
    ],
    [
        'kode_anggaran' => 'B.4.9',
        'nama_anggaran' => 'Pelaksanaan Orang/ Kegiatan',
        'satuan' => 'Kegiatan',
        'nominal' => 1600000,
    ],
    [
        'kode_anggaran' => 'B.5.1',
        'nama_anggaran' => '1. Reviewer dari Luar UTS Orang/Makalah',
        'satuan' => 'Paket',
        'nominal' => 150000,
    ],
    [
        'kode_anggaran' => 'B.5.2',
        'nama_anggaran' => '1. 1. Honorarium Pembantu Peneliti/Pengabdi kepada Masyarakat/Perekayasa',
        'satuan' => 'Orang/Jam',
        'nominal' => 25000,
    ],
    [
        'kode_anggaran' => 'B.5.2',
        'nama_anggaran' => '2. 2. Honorarium Koordinator Peneliti/Pengabdi kepada Masyarakat/Perekayasa',
        'satuan' => 'Orang/Bulan',
        'nominal' => 420000,
    ],
    [
        'kode_anggaran' => 'B.5.2',
        'nama_anggaran' => '3. 3. Honorarium Sekretariat Peneliti/Pengabdi kepada Masyarakat/Perekayasa',
        'satuan' => 'Orang/Bulan',
        'nominal' => 300000,
    ],
    [
        'kode_anggaran' => 'B.5.2',
        'nama_anggaran' => '4. Honorarium Pengolah Data Penelitian/',
        'satuan' => 'Paket',
        'nominal' => 1540000,
    ],
    [
        'kode_anggaran' => 'B.5.2',
        'nama_anggaran' => '5. Honorarium Petugas Survei Orang/',
        'satuan' => 'Paket',
        'nominal' => 20000,
    ],
    [
        'kode_anggaran' => 'B.5.2',
        'nama_anggaran' => '6. Honorarium Pembantu Lapangan',
        'satuan' => 'Orang/Hari',
        'nominal' => 80000,
    ],
    [
        'kode_anggaran' => 'B.5.3',
        'nama_anggaran' => '1 Komite Penilaian/Reviewer Proposal Proposal',
        'satuan' => 'Paket',
        'nominal' => 150000,
    ],
    [
        'kode_anggaran' => 'B.5.3',
        'nama_anggaran' => 'Laporan Antara Laporan',
        'satuan' => 'Paket',
        'nominal' => 500000,
    ],
    [
        'kode_anggaran' => 'B.5.3',
        'nama_anggaran' => 'Laporan Akhir Laporan',
        'satuan' => 'Paket',
        'nominal' => 1000000,
    ],
    [
        'kode_anggaran' => 'C.1',
        'nama_anggaran' => 'd. Biaya Pelatihan Capacity Building/ Softskill Orang/Kali/',
        'satuan' => 'Orang/Kali',
        'nominal' => 200000,
    ],
    [
        'kode_anggaran' => 'C.3',
        'nama_anggaran' => 'a. Pegawai',
        'satuan' => 'Orang/Kejadian',
        'nominal' => 2500000,
    ],
    [
        'kode_anggaran' => 'C.3',
        'nama_anggaran' => 'b. Suami/lstri Sah Pertama',
        'satuan' => 'Orang/Kejadian',
        'nominal' => 2000000,
    ],
    [
        'kode_anggaran' => 'C.3',
        'nama_anggaran' => 'c. Anak/Ayah/Ibu Kandung',
        'satuan' => 'Orang/Kejadian',
        'nominal' => 1500000,
    ],
    [
        'kode_anggaran' => 'C.3',
        'nama_anggaran' => '4. 4. Kesejahteraan Pegawai Menjelang Hari Raya Idul Fitri',
        'satuan' => 'Orang/Kegiatan',
        'nominal' => 300000,
    ],
    [
        'kode_anggaran' => 'C.3',
        'nama_anggaran' => 'a. Menyebabkan cacat permanen',
        'satuan' => 'Orang/Kejadian',
        'nominal' => 10000000,
    ],
    [
        'kode_anggaran' => 'C.3',
        'nama_anggaran' => 'b. Santunan operasi besar',
        'satuan' => 'Orang/Kejadian',
        'nominal' => 5000000,
    ],
    [
        'kode_anggaran' => 'C.3',
        'nama_anggaran' => 'c. Santunan operasi sedang',
        'satuan' => 'Orang/Kejadian',
        'nominal' => 3000000,
    ],
    [
        'kode_anggaran' => 'C.3',
        'nama_anggaran' => 'd. Santunan operasi kecil',
        'satuan' => 'Orang/Kejadian',
        'nominal' => 1000000,
    ],
    [
        'kode_anggaran' => 'C.3',
        'nama_anggaran' => '1 Juara I 5.000.000 7.000.000',
        'satuan' => 'Prestasi',
        'nominal' => 8000000,
    ],
    [
        'kode_anggaran' => 'C.3',
        'nama_anggaran' => '2 Juara II 3.000.000 5.000.000',
        'satuan' => 'Prestasi',
        'nominal' => 6000000,
    ],
    [
        'kode_anggaran' => 'C.3',
        'nama_anggaran' => '3 Juara III 2.000.000 3.000.000',
        'satuan' => 'Prestasi',
        'nominal' => 4000000,
    ],
    [
        'kode_anggaran' => 'C.3',
        'nama_anggaran' => '4 Penghargaan Khusus 1.000.000 2.000.000',
        'satuan' => 'Prestasi',
        'nominal' => 3000000,
    ],
    [
        'kode_anggaran' => 'D.2',
        'nama_anggaran' => '1 Juara I 2.500.000 4.000.000',
        'satuan' => 'Prestasi',
        'nominal' => 3750000,
    ],
    [
        'kode_anggaran' => 'D.2',
        'nama_anggaran' => '2 Juara II 1.500.000 2.000.000',
        'satuan' => 'Prestasi',
        'nominal' => 2500000,
    ],
    [
        'kode_anggaran' => 'D.2',
        'nama_anggaran' => '3 Juara III 1.500.000',
        'satuan' => 'Prestasi',
        'nominal' => 1000000,
    ],
    [
        'kode_anggaran' => 'D.2',
        'nama_anggaran' => '4 Penghargaan Khusus 700.000 1.000.000',
        'satuan' => 'Prestasi',
        'nominal' => 5000000,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '1 Juara I 1.000.000 1.200.000',
        'satuan' => 'Prestasi',
        'nominal' => 1500000,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '2 Juara II 750.000',
        'satuan' => 'Prestasi',
        'nominal' => 1000000,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '3 Juara lII 500.000',
        'satuan' => 'Prestasi',
        'nominal' => 750000,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '4 Penghargaan Khusus',
        'satuan' => 'Prestasi',
        'nominal' => 500000,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '1. Kewirausaan lndividu',
        'satuan' => 'Kegiatan',
        'nominal' => 5000000,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '2. Kewirausahaan Kelompok',
        'satuan' => 'Kegiatan',
        'nominal' => 8000000,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '1 Bantuan insentif delegasi lomba tingkat provinsi/universitas Lomba/',
        'satuan' => 'Paket',
        'nominal' => 200000,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '2 Bantuan insentif delegasi lomba tingkat nasional Lomba/',
        'satuan' => 'Paket',
        'nominal' => 300000,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '3 Bantuan insentif delegasi lomba tingkat internasional Lomba/',
        'satuan' => 'Paket',
        'nominal' => 500000,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '4 Bantuan hadiah penyelenggaraan lomba tingkat propinsi Kategori',
        'satuan' => 'Paket',
        'nominal' => 1000000,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '5 Bantuan hadiah penyelenggaraan lomba tingkat nasional Kategori',
        'satuan' => 'Paket',
        'nominal' => 2000000,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '6 Bantuan hadiah penyelenggaraan lomba tingkat internasional Kategori',
        'satuan' => 'Paket',
        'nominal' => 3000000,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '7 Bantuan operasional penyelenggaraan lomba/lokakarya/seminar/simposium/ pelatihan/workshop/diseminasi/sosialisasi/ sarasehan/diskusi terumpun (Focus Group Discusion) tingkat propinsi',
        'satuan' => 'Kegiatan',
        'nominal' => 1000000,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '8 Bantuan operasional penyelenggaraan lomba/lokakarya/seminar/simposium/ pelatihan/workshop/diseminasi/sosialisasi/ sarasehan/diskusi terumpun (Focus Group Discusion) tingkat nasional',
        'satuan' => 'Kegiatan',
        'nominal' => 2000000,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '9 Bantuan operasional penyelenggaraan lomba/lokakarya/seminar/simposium/ pelatihan/workshop/diseminasi/sosialisasi/ sarasehan/diskusi terumpun (Focus Group Discusion) tingkat internasional',
        'satuan' => 'Kegiatan',
        'nominal' => 3000000,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '2 Pakaian Dinas UTS Stel',
        'satuan' => 'Paket',
        'nominal' => 500000,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '3 Seragam Dies Natalis UTS 1 Stel/tahun',
        'satuan' => 'Paket',
        'nominal' => 100000,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '4 Kaos/ Atribut lainnya untuk Kegiatan Pelatihan Capacity Building/ Softskill Unit Kerja Orang/Unit /Tahun',
        'satuan' => 'Kegiatan',
        'nominal' => 100000,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '5 Pakaian Kerja Satpam Stel',
        'satuan' => 'Paket',
        'nominal' => 1235000,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '1 Karangan Bunga',
        'satuan' => 'Orang/Kegiatan',
        'nominal' => 500000,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '1 Chicago 12.733 6.891',
        'satuan' => 'Paket',
        'nominal' => 3662,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '2 Houstan 12.635 6.487',
        'satuan' => 'Paket',
        'nominal' => 3591,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '3 Los Angeles 11.411 5.925',
        'satuan' => 'Paket',
        'nominal' => 3242,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '4 New York 15.101 6.179',
        'satuan' => 'Paket',
        'nominal' => 3839,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '5 Ottawa 12.266 6.924',
        'satuan' => 'Paket',
        'nominal' => 4083,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '6 San Fransisco 13.438 7.138',
        'satuan' => 'Paket',
        'nominal' => 2987,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '7 Toronto 1.175 8.564',
        'satuan' => 'Paket',
        'nominal' => 3201,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '8 Vancouver 10.902 7.458',
        'satuan' => 'Paket',
        'nominal' => 3277,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '9 Washington 1.515 8.652',
        'satuan' => 'Paket',
        'nominal' => 3930,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '10 Bogota 18.399 9.426',
        'satuan' => 'Paket',
        'nominal' => 7713,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '11 Brazilia 16.393 597',
        'satuan' => 'Paket',
        'nominal' => 11518,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '12 Boenos Aires 23.000 15.300',
        'satuan' => 'Paket',
        'nominal' => 10400,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '13 Caracas 23.128 13.837',
        'satuan' => 'Paket',
        'nominal' => 6825,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '14 Paramaribo 15.018 9.494',
        'satuan' => 'Paket',
        'nominal' => 7353,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '15 Santiago de Chile 21.874 15.539',
        'satuan' => 'Paket',
        'nominal' => 8900,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '16 Quito 17.325 16.269',
        'satuan' => 'Paket',
        'nominal' => 12127,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '17 Lima 8.263 8.263',
        'satuan' => 'Paket',
        'nominal' => 5038,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '18 Meksiko 11.822 7.831',
        'satuan' => 'Paket',
        'nominal' => 3966,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '19 Havana 14.702 11.223',
        'satuan' => 'Paket',
        'nominal' => 7335,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '20 Panama 15.532 9.306',
        'satuan' => 'Paket',
        'nominal' => 6195,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '21 Vienna 1.052 4.177',
        'satuan' => 'Paket',
        'nominal' => 3357,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '22 Brussels 10.713 387',
        'satuan' => 'Paket',
        'nominal' => 5994,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '23 Marseilles 1.085 5.074',
        'satuan' => 'Paket',
        'nominal' => 3541,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '24 Paris 10.724 6.085',
        'satuan' => 'Paket',
        'nominal' => 3331,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '25 Berlin 10.277 6.085',
        'satuan' => 'Paket',
        'nominal' => 3331,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '26 Bonn 10.945 5.023',
        'satuan' => 'Paket',
        'nominal' => 3753,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '27 Hamburg 9.938 7.639',
        'satuan' => 'Paket',
        'nominal' => 4108,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '28 Geneva 8.166 537',
        'satuan' => 'Paket',
        'nominal' => 4333,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '29 Amsterdam 8.216 5.898',
        'satuan' => 'Paket',
        'nominal' => 3331,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '30 Den haag 8.216 5.898',
        'satuan' => 'Paket',
        'nominal' => 3331,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '31 Frankfurt 766 4.037',
        'satuan' => 'Paket',
        'nominal' => 1065,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '32 Kopenhagen 9.696 4.920',
        'satuan' => 'Paket',
        'nominal' => 3730,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '33 Helsinki 10.023 5.931',
        'satuan' => 'Paket',
        'nominal' => 3681,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '34 Stockholm 9.917 5.506',
        'satuan' => 'Paket',
        'nominal' => 3433,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '35 London 1.141 7.293',
        'satuan' => 'Paket',
        'nominal' => 4153,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '36 Oslo 9.856 4.773',
        'satuan' => 'Paket',
        'nominal' => 4049,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '37 Sarajevo 11.778 7.129',
        'satuan' => 'Paket',
        'nominal' => 6033,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '38 Zagreb 16.974 10.177',
        'satuan' => 'Paket',
        'nominal' => 5182,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '39 Athens 14.911 9.256',
        'satuan' => 'Paket',
        'nominal' => 8041,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '40 Lisbon 9.309 4.746',
        'satuan' => 'Paket',
        'nominal' => 3383,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '41 Madrid 10.393 4.767',
        'satuan' => 'Paket',
        'nominal' => 3631,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '42 Roma 10.000 6.000',
        'satuan' => 'Paket',
        'nominal' => 4500,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '43 Beograd 10.318 6.404',
        'satuan' => 'Paket',
        'nominal' => 5564,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '44 Vatican 10.000 6.000',
        'satuan' => 'Paket',
        'nominal' => 4500,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '45 Bratislava 7.125 4.423',
        'satuan' => 'Paket',
        'nominal' => 3842,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '46 Bucharest 8.839 4.982',
        'satuan' => 'Paket',
        'nominal' => 4113,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '47 Kiev 1.086 6.029',
        'satuan' => 'Paket',
        'nominal' => 5193,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '48 Mokcow 9.537 7.206',
        'satuan' => 'Paket',
        'nominal' => 5143,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '49 Praha 19.318 11.848',
        'satuan' => 'Paket',
        'nominal' => 6748,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '50 Sofia 7.473 6.346',
        'satuan' => 'Paket',
        'nominal' => 3612,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '51 Warsawa 10.777 5.052',
        'satuan' => 'Paket',
        'nominal' => 3447,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '52 Budapest 8.839 5.979',
        'satuan' => 'Paket',
        'nominal' => 2187,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '53 Dakkar 12.900 9.848',
        'satuan' => 'Paket',
        'nominal' => 8555,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '54 Abuja 10.281 7.848',
        'satuan' => 'Paket',
        'nominal' => 6818,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '55 Addis Ababa 7.700 5.808',
        'satuan' => 'Paket',
        'nominal' => 5552,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '56 Nairobi 8.732 7.966',
        'satuan' => 'Paket',
        'nominal' => 6081,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '57 Antananarivo 11.779 9.000',
        'satuan' => 'Paket',
        'nominal' => 8282,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '58 Dar Es Salam 8.947 6.599',
        'satuan' => 'Paket',
        'nominal' => 5733,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '59 Harare 11.118 10.600',
        'satuan' => 'Paket',
        'nominal' => 5747,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '60 Windhoek 18.241 751',
        'satuan' => 'Paket',
        'nominal' => 11774,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '61 Cape Town 17.182 9.703',
        'satuan' => 'Paket',
        'nominal' => 8429,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '62 Johannesburg 12.943 9.802',
        'satuan' => 'Paket',
        'nominal' => 7216,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '63 Maputo 11.255 8.524',
        'satuan' => 'Paket',
        'nominal' => 6275,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '64 Pretoria 12.943 9.802',
        'satuan' => 'Paket',
        'nominal' => 7216,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '65 Algiers 9.536 6.593',
        'satuan' => 'Paket',
        'nominal' => 5710,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '66 Kairo 8.683 7.122',
        'satuan' => 'Paket',
        'nominal' => 4483,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '67 Khartoum 5.904 4.507',
        'satuan' => 'Paket',
        'nominal' => 3915,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '68 Rabbat 891 7.721',
        'satuan' => 'Paket',
        'nominal' => 5665,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '69 Tripoli 6.551 5.706',
        'satuan' => 'Paket',
        'nominal' => 4975,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '70 Tunisia 9.419 5.018',
        'satuan' => 'Paket',
        'nominal' => 3619,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '71 Manama 6.573 6.154',
        'satuan' => 'Paket',
        'nominal' => 4827,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '72 Baghdad 5.433 4.148',
        'satuan' => 'Paket',
        'nominal' => 3545,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '73 Amman 7.561 6.431',
        'satuan' => 'Paket',
        'nominal' => 3545,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '74 Kuwait 6.771 311',
        'satuan' => 'Paket',
        'nominal' => 4273,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '75 Beirut 7.703 4.490',
        'satuan' => 'Paket',
        'nominal' => 3730,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '76 Doha 5.216 3.639',
        'satuan' => 'Paket',
        'nominal' => 2745,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '77 Damascus 8.684 539',
        'satuan' => 'Paket',
        'nominal' => 3325,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '78 Ankara 9.449 6.643',
        'satuan' => 'Paket',
        'nominal' => 3581,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '79 Abu dhabi 5.283 4.976',
        'satuan' => 'Paket',
        'nominal' => 2727,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '80 Sanaa 8.205 5.878',
        'satuan' => 'Paket',
        'nominal' => 3679,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '81 Jeddah 6.446 3.785',
        'satuan' => 'Paket',
        'nominal' => 3321,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '82 Muscat 6.469 5.156',
        'satuan' => 'Paket',
        'nominal' => 3727,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '83 Riyadh 5.359 3.510',
        'satuan' => 'Paket',
        'nominal' => 3000,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '84 Istambul 11.061 4.435',
        'satuan' => 'Paket',
        'nominal' => 2467,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '85 Dubai 4.207 4.207',
        'satuan' => 'Paket',
        'nominal' => 1920,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '86 Tashkent 13.617 8.453',
        'satuan' => 'Paket',
        'nominal' => 7343,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '87 Astana 13.661 12.089',
        'satuan' => 'Paket',
        'nominal' => 8962,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '88 Baku 13.234 8.556',
        'satuan' => 'Paket',
        'nominal' => 2281,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '89 Beijing 2.595 2.140',
        'satuan' => 'Paket',
        'nominal' => 1623,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '90 Hongkong 3.028 2.633',
        'satuan' => 'Paket',
        'nominal' => 1257,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '91 Oska 3.204 2.686',
        'satuan' => 'Paket',
        'nominal' => 1864,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '92 Tokyo 3.734 2.675',
        'satuan' => 'Paket',
        'nominal' => 1835,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '93 Pyongyang 4.040 2.220',
        'satuan' => 'Paket',
        'nominal' => 1660,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '94 Seoul 3.233 2.966',
        'satuan' => 'Paket',
        'nominal' => 1737,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '95 Shanghai 3.122 2.749',
        'satuan' => 'Paket',
        'nominal' => 1304,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '96 Guangzhou 3.122 2.749',
        'satuan' => 'Paket',
        'nominal' => 1304,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '97 Kaboul 6.307 3.905',
        'satuan' => 'Paket',
        'nominal' => 3208,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '98 Teheran 5.800 4.600',
        'satuan' => 'Paket',
        'nominal' => 3200,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '99 Colombo 3.119 2.562',
        'satuan' => 'Paket',
        'nominal' => 1628,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '100 Dhaka 3.063 2.417',
        'satuan' => 'Paket',
        'nominal' => 1092,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '101 Islamabad 5.482 3.333',
        'satuan' => 'Paket',
        'nominal' => 2501,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '102 Karachi 4.226 3.633',
        'satuan' => 'Paket',
        'nominal' => 2321,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '103 New delhi 3.500 2.500',
        'satuan' => 'Paket',
        'nominal' => 1500,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '104 Mumbai 3.063 2.417',
        'satuan' => 'Paket',
        'nominal' => 1092,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '105 Bandar seri bengawan 1.628 919',
        'satuan' => 'Paket',
        'nominal' => 1147,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '106 Bangkok 2.344 823',
        'satuan' => 'Paket',
        'nominal' => 1155,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '107 Davao city 2.757 2.558',
        'satuan' => 'Paket',
        'nominal' => 1641,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '109 Hanoi 1.833 1.833',
        'satuan' => 'Paket',
        'nominal' => 1656,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '110 Ho chi minh 1.677 1.503',
        'satuan' => 'Paket',
        'nominal' => 1235,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '111 Johor bahru 911 525',
        'satuan' => 'Paket',
        'nominal' => 1195,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '112 Kota Kinabalu 1.894 694',
        'satuan' => 'Paket',
        'nominal' => 1427,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '113 Kuala lumpur 659 585',
        'satuan' => 'Paket',
        'nominal' => 1158,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '114 Kuching 2.659 364',
        'satuan' => 'Paket',
        'nominal' => 1900,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '115 Manila 2.453 115',
        'satuan' => 'Paket',
        'nominal' => 1614,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '117 Phnom Penh 2.202 1.981',
        'satuan' => 'Paket',
        'nominal' => 1627,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '119 Vientiane 2.274 142',
        'satuan' => 'Paket',
        'nominal' => 2025,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '120 Yangon 1.468 1.212',
        'satuan' => 'Paket',
        'nominal' => 1053,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '121 Tawau 1.894 694',
        'satuan' => 'Paket',
        'nominal' => 1427,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '122 Songkhla 2.344 823',
        'satuan' => 'Paket',
        'nominal' => 1155,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '123 Canberra 6.304 6.304',
        'satuan' => 'Paket',
        'nominal' => 2500,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '124 Darwin 6.689 4.900',
        'satuan' => 'Paket',
        'nominal' => 3964,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '125 Melbourne 4.886 3.814',
        'satuan' => 'Paket',
        'nominal' => 2858,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '126 Noumea 694 5.917',
        'satuan' => 'Paket',
        'nominal' => 1916,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '127 Pert 5.771 1.801',
        'satuan' => 'Paket',
        'nominal' => 1525,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '128 Port Moresby 1.709 13.835',
        'satuan' => 'Paket',
        'nominal' => 8252,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '129 Suva 12.668 4.461',
        'satuan' => 'Paket',
        'nominal' => 2669,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '130 Sydney 4.629 4.237',
        'satuan' => 'Paket',
        'nominal' => 2557,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '131 Vanimo 3.318 2.740',
        'satuan' => 'Paket',
        'nominal' => 2380,
    ],
    [
        'kode_anggaran' => 'D.3',
        'nama_anggaran' => '131 Wellington 1.175 983',
        'satuan' => 'Paket',
        'nominal' => 4120,
    ],
]
        ];

        // Masukkan ke database (Gunakan upsert agar tidak duplikat jika dijalankan ulang)
        // Asumsi nama tabel adalah 'rincian_anggarans' atau 'akun_anggarans' 
        // Sesuaikan dengan nama tabel Master Anggaran di database Anda.
        foreach ($data as $item) {
            DB::table('rincian_anggarans')->updateOrInsert(
                ['kode_anggaran' => $item['kode_anggaran']], // Kunci pengecekan
                [
                    'nama_anggaran' => $item['nama_anggaran'],
                    'satuan' => $item['satuan'],
                    'nominal' => $item['nominal'], // Pastikan kolom ini ada di migrasi (misal: nominal atau plafon)
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ]
            );
        }
    }
}